import type { Metadata } from "next";
import "./globals.css";
import AppHeader from "@vtapp/components/AppHeader";
import Footer from "@vtapp/components/Footer";
import dynamic from "next/dynamic";

const DynamicAnimationBackground = dynamic(
  () => import("../components/BackgroundAnimation"),
  {
    ssr: false,
  }
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black min-h-screen scroll-smooth">
        <DynamicAnimationBackground />
        <AppHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
